assets = {directory = "./public/"}
compatibility_date = "2024-11-09"
main = "src/index.ts"
name = "appsinprogress-oauth"

[[unsafe.bindings]]
name = "RATE_LIMITER"
namespace_id = "2"
type = "ratelimit"
# 10 requests per 10 seconds
simple = {limit = 10, period = 10}

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
